"""add required_role to task_categories

Revision ID: 96df6da64fe8
Revises: 9f26d9b32887
Create Date: 2026-02-12 15:35:11.311551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96df6da64fe8'
down_revision: Union[str, None] = '9f26d9b32887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('task_categories', sa.Column('required_role', sa.String(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE task_categories SET required_role = 'team_member' WHERE required_role IS NULL")
    # Make column non-nullable
    op.alter_column('task_categories', 'required_role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_categories', 'required_role')
    # ### end Alembic commands ###
