"""remove_task_lists_simplify_structure

Revision ID: 117e2b415849
Revises: 9c2f10b18c75
Create Date: 2026-01-01 13:40:33.448691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '117e2b415849'
down_revision: Union[str, None] = '9c2f10b18c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, add the new project_id column to tasks (nullable temporarily)
    op.add_column('tasks', sa.Column('project_id', sa.Integer(), nullable=True))

    # Copy data from task_lists to tasks.project_id
    op.execute("""
        UPDATE tasks
        SET project_id = task_lists.project_id
        FROM task_lists
        WHERE tasks.task_list_id = task_lists.id
    """)

    # Make project_id non-nullable now that data is migrated
    op.alter_column('tasks', 'project_id', nullable=False)

    # Drop the foreign key constraint and column from tasks
    op.drop_constraint('tasks_task_list_id_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'task_list_id')

    # Create new foreign key
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'])

    # Now drop the task_lists table
    op.drop_index('ix_task_lists_id', table_name='task_lists')
    op.drop_table('task_lists')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_list_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_task_list_id_fkey', 'tasks', 'task_lists', ['task_list_id'], ['id'])
    op.drop_column('tasks', 'project_id')
    op.create_table('task_lists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='task_lists_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='task_lists_pkey')
    )
    op.create_index('ix_task_lists_id', 'task_lists', ['id'], unique=False)
    # ### end Alembic commands ###
